name: homeopathyandradiesthesy
favicon: null
layout_spectrum: 0.49572317488491535
typography_spectrum: 0.16552766459062696
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.819377678912133
  lightness: 0.32937807007692754
  saturation: 0.920136695727706
  rhythmicContrast: 0.7277955620083958
purpose: []
